version: '3'

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    container_name: project_nginx
    depends_on:
      - app
      
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: project_app
    depends_on:
      - db
  
  node:
    image: "node:20"
    user: "node"
    working_dir: /var/www
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/var/www
    expose:
      - "8081"
    ports: # use if it is necessary to expose the container to the host machine
      - "8001:8001"
    command: "npm start"

  
  
  db:
    image: postgres:16.4
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test_shop_2
      POSTGRES_PASSWORD: 12345
    ports:
      - 8101:5432
    container_name: project_db
    
    